// src/entrypoints/options/App.tsx
import { useState, useEffect } from "react"
import Button from "@/entrypoints/components/ui/button"
import "../global.css"
import { isExtensionActive } from "@/utils/storage"

const Popup: React.FC = () => {
  const [isActive, setIsActive] = useState<boolean>(true)

  useEffect(() => {
    const initializeState = async () => {
      try {
        const value = await isExtensionActive.getValue()
        setIsActive(value)
      } catch (err) {
        console.error("Error while getting extension active storage information", err)
      }
    }

    initializeState()

    isExtensionActive.watch((active: boolean) => {
      setIsActive(active)
    })
  }, [])

  const toggleExtension = async () => {
    const currentState = await isExtensionActive.getValue()
    await isExtensionActive.setValue(!currentState)
  }

  return (
    <main className="min-h-screen p-2 flex flex-col font-main font-medium bg-primary text-white">
      <h1>LLM Toolbox</h1>
      <p>Extension is = {String(isActive)}</p>
      <Button className="min-w-20 w-24" onClick={toggleExtension}>
        {isActive ? "Deactivate" : "Activate"}
      </Button>
    </main>
  )
}

export default Popup

// src/entrypoints/popup/App.svelte
<script lang="ts">
  import "../global.css"
  import { isExtensionActive } from "../../utils/storage"

  let isActive = $state(true)

  isExtensionActive.watch((active) => {
    isActive = active
  })

  $effect(() => {
    isExtensionActive
      .getValue()
      .then((value) => {
        isActive = value
      })
      .catch((err) => {
        console.error("Error while getting extension active storage information", err)
      })
  })

  async function toggleExtension() {
    const isActive = await isExtensionActive.getValue()
    await isExtensionActive.setValue(!isActive)
  }
</script>

<main class="min-w-48 min-h-24 p-2 flex flex-col justify-center items-center">
  <h1>LLM Toolbox</h1>
  <p>Extension is = {isActive}</p>
  <button onclick={toggleExtension} class="border p-2 bg-black text-white rounded-2xl cursor-pointer"
    >Toggle Extension</button
  >
</main>
