// src/entrypoints/components/ui/button.tsx
import { twMerge } from "tailwind-merge"

interface ButtonProps {
  onClick?: () => void
  children: React.ReactNode | string
  className?: string
}

export default function Button(props: ButtonProps) {
  return (
    <button
      {...props}
      role="button"
      onClick={props.onClick}
      className={twMerge(
        "p-2 rounded-md bg-black text-white cursor-pointer border border-transparent hover:border-white",
        props.className
      )}
    >
      {props.children}
    </button>
  )
}

// src/entrypoints/components/Button.svelte
<script lang="ts">
  import { type Snippet } from "svelte"
  import { twMerge } from "tailwind-merge"

  interface Props {
    className?: string
    children: Snippet
    onClick: () => void
    disabled?: boolean
  }

  let { className = "", children, onClick, disabled = false }: Props = $props()
</script>

<button class={twMerge("py-2 px-4 rounded-2xl border", className)} onclick={onClick} {disabled}>
  {@render children()}
</button>
